times = ('Flamengo', 'Corinthians', 'Palmeiras', 'Santos', 'Vasco', 'São Paulo', 'Cruzeiro', 'Atlético Mineiro', 'Internacional', 'Grêmio', 'Fluminense', 'Botafogo', 'Athletico Paranaense', 'Bahia', 'Vitória', 'Chapecoense', 'América', 'Ponte Preta')
print('-=-'*30)
print(f'Lista de times do Brasileirão: {times}')
print('-=-'*30)
print(f'Os 5 primeiros colocados: {times[:5]}')
print('-=-'*30)
print(f'Os 4 últimos são: {times[14:]}')
print('-=-'*30)
print(f'Times em ordem alfabética: {sorted(times)}')
print('-=-'*30)
print(f'O chapecoense está na {times.index("Chapecoense")}ª posição.')